set preview_images true
set preview_images_method kitty
set preview_script ~/.config/ranger/scope.sh
map <DELETE> delete
map DD shell -s trash-put %s
set show_hidden true
set sort_directories_first false
set sort mtime
